version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1